### ISSUE TITLE
i.e support

### ISSUE THREAD

**Issue by sewarts** [tycomo/generator-pwa-angular-core#1]
This doesn't work in i.e.

Have added polyfills for object.assign and array.from but have now hit brick wall.

Anyone resolved this?

**Comment by tycomo** [comment]
Hi there! Sorry for the delayed response.  I am working on an upgraded version now that will upgrade the template to use the newest version of Angular Universal and .NET Core 2.  This should fix a lot of the bugs with IE. Stay tuned for the release in the next few days!

Thanks!

**Comment by sewarts** [comment]
Great thanks. Did finally notice the polyfills for ie within the existing project and these solved most of the ie problems for now.
